import Card from './component/Cards';
import Modal from './component/Modal';
import Button1 from './component/Button';
import './App.css';
const App = () => {

  return (
    <>
      <Modal modalMainConatiner="modalMainConatiner" modalMainBody="modalMainBody ModalBackDesign modalBackDesigncolor" modalContantContainer="modalContantContainer" modalHeadingMain="modalHeadingMain" btnvalue="Hire Now!" classBtn1="classBtn1" classBtn1Animation="classBtn1Animation" modalHeading="modalHeading" modalHeadingGreadent1="modalHeadingGreadent1" modalHeadingGreadent2="modalHeadingGreadent2" modalDetail="modalDetail" btnContainer="btnContainer" modalRelative="modalRelative" modalCircleImage1="modalCircleImage1" modalCircleImage2="modalCircleImage2" modalCircleImage3="modalCircleImage3" modalCircleImage4="modalCircleImage4" modalCircleImage5="modalCircleImage5" modalCircleImage6="modalCircleImage6" modalCircleImage7="modalCircleImage7" modalCircleImage8="modalCircleImage8" modalCircleImage9="modalCircleImage9" imageCircle1="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-closeup-woman-03-p-500.jpeg" imageCircle2="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/testimonial-01-bright-webflow-uikit-p-500.jpeg" imageCircle3="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-03.jpg" imageCircle4="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-closeup-woman-02.jpg" imageCircle5="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-landscape-03-p-500.jpeg" imageCircle6="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-02_1.jpg" imageCircle7="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-02-p-500.jpeg" imageCircle8="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-01-p-500.jpeg" imageCircle9="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-01_1.jpg" modalValue1="Hire" modalValueG1="Remote" modalValueG2="Unicorn" modalValue2="Devs" modalValueDetal="Get matched with our elite group of hand-selected & rigorously vetted Unicorn Devs, assigned to you in 24 hours."/>
      
        {/* <Card cardContainer="cardContainer" layoutCard="layoutCard right" cardImageContainer="cardImageContainer imageConatinerGretdent1" imageSource="https://www.florin-pop.com/static/580a39549812457188f2acf1b8459d3f/47cd0/profile-card-design.png" cardDataContainer="cardDataContainer" heading="cardheading" textgreadent1="textgreadent1" headingvalue="Tell Us What" headingvalueG="You Need" paragvalue="Let us know your development needs, whether it's an individual developer or an entire tech team, we're here to help! A consultant will reach out to you to understand your requirements better prior to sourcing your talent." />
        <Card cardContainer="cardContainer" layoutCard="layoutCard left" cardImageContainer="cardImageContainer imageConatinerGretdent2" imageSource="https://www.florin-pop.com/static/580a39549812457188f2acf1b8459d3f/47cd0/profile-card-design.png" cardDataContainer="cardDataContainer" heading="cardheading" textgreadent1="textgreadent2" headingvalue="Tell Us What" headingvalueG="You Need" paragvalue="Let us know your development needs, whether it's an individual developer or an entire tech team, we're here to help! A consultant will reach out to you to understand your requirements better prior to sourcing your talent." />
        <Card cardContainer="cardContainer" layoutCard="layoutCard right" cardImageContainer="cardImageContainer imageConatinerGretdent1" imageSource="https://www.florin-pop.com/static/580a39549812457188f2acf1b8459d3f/47cd0/profile-card-design.png" cardDataContainer="cardDataContainer" heading="cardheading" textgreadent1="textgreadent1" headingvalue="Tell Us What" headingvalueG="You Need" paragvalue="Let us know your development needs, whether it's an individual developer or an entire tech team, we're here to help! A consultant will reach out to you to understand your requirements better prior to sourcing your talent." /> */}
    </>
  )
}
export default App;