import { Card, Card1 } from './component/Cards';
import Modal from './component/Modal';
import Button1 from './component/Button';
import { Title1Container, Title2Container } from './component/Title';
import fingerImg from "./asset/fingerprint.png"
import './App.css';
const App = () => {

  return (
    <>
      <div className='container1'>
        {/* <Modal modalMainConatiner="modalMainConatiner" modalMainBody="modalMainBody ModalBackDesign modalBackDesigncolor" modalContantContainer="modalContantContainer" modalHeadingMain="modalHeadingMain" btnvalue="Hire Now!" classBtn1="classBtn1" classBtn1Animation="classBtn1Animation" modalHeading="modalHeading" modalHeadingGreadent1="modalHeadingGreadent1" modalHeadingGreadent2="modalHeadingGreadent2" modalDetail="modalDetail" btnContainer="btnContainer" modalRelative="modalRelative" modalCircleImage1="modalCircleImage1" modalCircleImage2="modalCircleImage2" modalCircleImage3="modalCircleImage3" modalCircleImage4="modalCircleImage4" modalCircleImage5="modalCircleImage5" modalCircleImage6="modalCircleImage6" modalCircleImage7="modalCircleImage7" modalCircleImage8="modalCircleImage8" modalCircleImage9="modalCircleImage9" imageCircle1="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-closeup-woman-03-p-500.jpeg" imageCircle2="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/testimonial-01-bright-webflow-uikit-p-500.jpeg" imageCircle3="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-03.jpg" imageCircle4="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-closeup-woman-02.jpg" imageCircle5="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-landscape-03-p-500.jpeg" imageCircle6="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-02_1.jpg" imageCircle7="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-02-p-500.jpeg" imageCircle8="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-01-p-500.jpeg" imageCircle9="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/avatar-01_1.jpg" modalValue1="Hire" modalValueG1="Remote" modalValueG2="Unicorn" modalValue2="Devs" modalValueDetal="Get matched with our elite group of hand-selected & rigorously vetted Unicorn Devs, assigned to you in 24 hours." /> */}
        {/* <Title1Container title1HeadingLineholder="title1HeadingLineholder" title1ContainerMainContainer="title1ContainerMainContainer"  lineHolderColor2="lineHolderDesign lineHolderColor" lineHolderColor="rotate lineHolderDesign lineHolderColor" title1Heading="title1Heading" title1HeadingContant="title1HeadingContant" contantValueContainer="contantValueContainer" contantNocontainer="contantNocontainer" title1DetailContainer="title1DetailContainer" title1Image="title1Image" title1ImageSrc={fingerImg} title1MainHeading="title1MainHeading" title1HeadingH1="title1HeadingH1" title1HeadingH1G="textgreadent4" title1Detail="title1Detail" title1SnoValue="01" title1SnoHeadingValue="Get Start" title1MainHeadingValue="Steps to Hire" title1MainHeadingValueG="Talent" title1DetailValue="We provide a simple & straightforward hiring process to help you find highly-skilled remote tech talent in record time." /> */}
        {/* <Card cardContainer="cardContainer" layoutCard="layoutCard right" cardImageContainer="cardImageContainer imageConatinerGretdent1" imageSource="https://www.florin-pop.com/static/580a39549812457188f2acf1b8459d3f/47cd0/profile-card-design.png" cardDataContainer="cardDataContainer" heading="cardheading" textgreadent1="textgreadent1" headingvalue="Tell Us What" headingvalueG="You Need" paragvalue="Let us know your development needs, whether it's an individual developer or an entire tech team, we're here to help! A consultant will reach out to you to understand your requirements better prior to sourcing your talent." /> */}
        {/* <Card cardContainer="cardContainer" layoutCard="layoutCard left" cardImageContainer="cardImageContainer imageConatinerGretdent2" imageSource="https://www.florin-pop.com/static/580a39549812457188f2acf1b8459d3f/47cd0/profile-card-design.png" cardDataContainer="cardDataContainer" heading="cardheading" textgreadent1="textgreadent2" headingvalue="Tell Us What" headingvalueG="You Need" paragvalue="Let us know your development needs, whether it's an individual developer or an entire tech team, we're here to help! A consultant will reach out to you to understand your requirements better prior to sourcing your talent." /> */}
        {/* <Card cardContainer="cardContainer" layoutCard="layoutCard right" cardImageContainer="cardImageContainer imageConatinerGretdent1" imageSource="https://www.florin-pop.com/static/580a39549812457188f2acf1b8459d3f/47cd0/profile-card-design.png" cardDataContainer="cardDataContainer" heading="cardheading" textgreadent1="textgreadent1" headingvalue="Tell Us What" headingvalueG="You Need" paragvalue="Let us know your development needs, whether it's an individual developer or an entire tech team, we're here to help! A consultant will reach out to you to understand your requirements better prior to sourcing your talent." /> */}
        {/* <Title2Container title1HeadingLineholder2="title1HeadingLineholder2" title1ContainerMainContainer2="title1ContainerMainContainer2"  lineHolderColor2="lineHolderDesign lineHolderColor" lineHolderColor="rotate lineHolderDesign lineHolderColor" title1Heading="title1Heading" title1HeadingContant="title1HeadingContant" contantValueContainer="contantValueContainer" contantNocontainer="contantNocontainer" title1DetailContainer2="title1DetailContainer2" title1MainHeading="title1MainHeading" title1HeadingH1A="title1HeadingH1A" title1HeadingH1G="textgreadent4" title2SnoValue="03" title2SnoHeadingValue="TALENT" title2MainHeadingValue="Some of Our to Hire" title2MainHeadingValueG="Talents"  /> */}
        <Card1 card1Container="card1Container" card1Img="card1Img" card1Name="card1Name" card1Experience="card1Experience" card1NameValue="Rob Legaspi" card1ExperienceValue="Fullstack JS dev with 6 years of experience" card1ImgSource="https://d5gp1bgprhhde.cloudfront.net/wp-content/themes/unicorn-code/images/1601042335818-p-500.jpeg"/>
      </div>

    </>
  )
}
export default App;